services:
  postgres:
    image: postgres:15
    container_name: dogfood_db
    environment:
      POSTGRES_DB: dogfood_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: